/**
 * Renders pebble's `dist/site/css/tokens.css` from the token model.
 *
 * The output is deliberately byte-identical to pebble's `tokens/build.mjs` (header included),
 * which is what makes the app trustworthy as an editor: whatever it shows is what the build
 * produces. `src/lib/pebble/css.test.ts` asserts exactly that against a copy of the built file.
 *
 * Note on the model: the layers are stored *unwrapped* (`primitives` is `{color, spacing, …}`,
 * not `{primitives: {color, spacing, …}}`) because that is what the UI tree wants. Flattening
 * therefore passes the layer name in as the path prefix. Theme overrides stay wrapped, because
 * their root keys (`semantic`, and the stray `elevation`/`tab` in dark) are real token paths.
 */

import { flattenTokens, resolveTokens, sortTokenEntries, toCssValue, toCssVarName, type FlatTokens, type ResolveOptions } from './model.js'
import { fromSnapshot } from './load.js'
import type { PebbleTokens } from './types.js'

/**
 * The theme that lands on `:root`. Hardcoded here because `build.mjs` hardcodes it too — the
 * config's `defaultTheme` is a hint for the app's UI, not an input to the generated CSS.
 */
export const BASE_THEME_ID = 'light'

/** The three layers flattened into one path→value map, each path carrying its layer name. */
export const flattenLayers = (tokens: PebbleTokens): FlatTokens => ({
  ...flattenTokens(tokens.primitives, ['primitives']),
  ...flattenTokens(tokens.semantic, ['semantic']),
  // A component's root key *is* its path (`button.primary.background.default`).
  ...flattenTokens(tokens.components),
})

/** One theme's sparse overrides, flattened so they can be merged over the layers leaf by leaf. */
export const themeOverrides = (tokens: PebbleTokens, themeId: string): FlatTokens => flattenTokens(tokens.themes[themeId] ?? {})

/**
 * The final declarations of one theme. `preserveReferences` defaults to the build's behaviour
 * (`var(--…)` inside component tokens); pass `false` to get every value substituted in full.
 */
export const resolveTheme = (tokens: PebbleTokens, themeId: string, options: ResolveOptions = { preserveReferences: true }): FlatTokens =>
  resolveTokens({ ...flattenLayers(tokens), ...themeOverrides(tokens, themeId) }, options)

export const themeSelector = (themeId: string): string => (themeId === BASE_THEME_ID ? ':root' : `:root[data-theme="${themeId}"]`)

/** One `selector { … }` block, declarations sorted the way the build sorts them. */
export const generateThemeCss = (themeId: string, resolved: FlatTokens): string => {
  const declarations = sortTokenEntries(Object.entries(resolved)).map(([path, value]) => `  ${toCssVarName(path)}: ${toCssValue(value)};`)

  return `${themeSelector(themeId)} {\n${declarations.join('\n')}\n}`
}

/** The header comment, with the timestamp the caller stamps in. */
export const tokensCssHeader = (generatedAt: string): string => `/**
 * Design Tokens
 * Generated: ${generatedAt}
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated from design token JSON files
 * Run 'npm run tokens:build' to regenerate
 */

`

/** The whole file: header, then one block per theme in `config.themes` order. */
export const generateTokensCss = (tokens: PebbleTokens, generatedAt: string = new Date().toISOString()): string => {
  const blocks = tokens.config.themes.map((theme) => generateThemeCss(theme.id, resolveTheme(tokens, theme.id)))

  return `${tokensCssHeader(generatedAt)}${blocks.join('\n\n')}\n`
}

/**
 * Build a CSS file from the snapshot JSON shape used by the app. This is the same output as the
 * Pebble build, but takes the JSON object directly so we can write a dist artifact without the
 * app having to fetch it from the browser.
 */
export const generateTokensCssFile = (json: unknown, generatedAt: string = new Date().toISOString()): string => {
  const tokens = fromSnapshot(json) ?? (json as PebbleTokens | null)

  if (!tokens || !tokens.config || !tokens.primitives || !tokens.semantic || !tokens.components) {
    throw new Error('tokens.css generation requires a pebble token snapshot object')
  }

  return generateTokensCss(tokens, generatedAt)
}

export interface ThemeSummary {
  themeId: string
  name: string
  selector: string
  /** How many custom properties the block holds. */
  variables: number
  /** How many of those values are overridden by the theme rather than the layers. */
  overrides: number
}

/** Per-theme counts, for the app's header and for tests that pin the shape of the file. */
export const summariseThemes = (tokens: PebbleTokens): ThemeSummary[] =>
  tokens.config.themes.map((theme) => {
    const resolved = resolveTheme(tokens, theme.id)
    const overrides = themeOverrides(tokens, theme.id)

    return {
      themeId: theme.id,
      name: theme.name,
      selector: themeSelector(theme.id),
      variables: Object.keys(resolved).length,
      overrides: Object.keys(overrides).length,
    }
  })

/**
 * The generated file, memoised per token set: the app re-renders on every keystroke in its search
 * box, and building 903 declarations each time is not free. A new `tokens` object (every edit
 * produces one) simply misses the cache.
 */
const cssCache = new WeakMap<PebbleTokens, string>()

export const cachedTokensCss = (tokens: PebbleTokens): string => {
  const known = cssCache.get(tokens)
  if (known !== undefined) return known

  const css = generateTokensCss(tokens)
  cssCache.set(tokens, css)

  return css
}
